{ config, pkgs, userSettings, ... }:
{
  # Program configs covered by Home Manager
  programs = {
    # Let Home Manager install and manage itself.
    home-manager.enable = true;
    # Git
    git = {
      enable = true;
      userName = userSettings.git.fullName;
      userEmail = userSettings.git.email;
      # Git LFS
      lfs.enable = true;
    };
    # GitHub CLI
    gh.enable = true;
    # LazyGit - Dependency for Diana's Helix configuration
    lazygit.enable = true;
    # GnuPG
    gpg.enable = true;
    # SSH
    ssh.enable = true;
    # Helix
    helix = {
      enable = true;
      # Diana's Helix configuration
      # Ported from github:dianaw353/dotfiles-v2/main/dot_config/helix/config.toml
      settings = {
        theme = "base16_transparent";
        editor = {
          mouse = false;
          bufferline = "always";
          true-color = true;
          color-modes = true;
          soft-wrap.enable = true;
          cursor-shape.insert = "bar";
        };
      };
    };
    # OBS Studio
    obs-studio.enable = true;
    # Tmate
    tmate.enable = true;
    # HyFetch
    hyfetch = {
      enable = true;
      # Ported from my preferences generated by going through the setup.
      settings = {
        preset = userSettings.hyfetch.gender;
        mode = "rgb";
        light_dark = userSettings.hyfetch.light_dark;
        lightness = userSettings.hyfetch.lightness;
        color_align = {
          mode = userSettings.hyfetch.colorMode;
        };
        backend = userSettings.hyfetch.backend;
      };
    };
    # zsh-nix-shell
    zsh = {
      enable = true;
      enableCompletion = true;
      plugins = [
        {
          name = "zsh-nix-shell";
          file = "nix-shell.plugin.zsh";
          src = pkgs.fetchFromGitHub {
            owner = "chisui";
            repo = "zsh-nix-shell";
            rev = "v0.8.0";
            sha256 = "1lzrn0n4fxfcgg65v0qhnj7wnybybqzs4adz7xsrkgmcsr0ii8b7";
          };
        }
      ];
    };
    # Distrobox config is available only on unstable channel.
    distrobox = {
      enable = true;
      containers = {
        ubuntu = {
          image = "ubuntu:latest";
          init_hooks = [
            ''
              if ! apt search bifrost | grep "bifrost/.*installed"; then
                wget -O /tmp/bifrost.deb https://github.com/zacharee/SamloaderKotlin/releases/download/1.20.1/bifrost_1.20.1_amd64.deb
                apt update
                apt -y upgrade
                apt -y install /tmp/bifrost.deb
                rm /tmp/bifrost.deb
              fi
            ''
            "chsh -s /bin/bash linda"
          ];
        };
        # Pisilinux Docker container doesn't have everything required for Distrobox to consider complete.
        #pisi = {
        #  image = "docker.io/pisilinux/chroot:latest";
        #};
      };
    };
    kodi.enable = true;
  };

  # Other packages not covered by Home Manager
  home.packages = with pkgs; [
    # Nice-to-have KDE programs
    kdePackages.kate
    kdePackages.kcalc
    # General internet
    telegram-desktop
    #(callPackage ../../pkgs/discord/default.nix { })
    discord
    signal-desktop
    spotify
    transmission_4-qt6
    # Markdown
    kdePackages.ghostwriter
    # Programming with Python+Qt5
    python312Packages.notebook
    python312Packages.pyqt5
    libsForQt5.qt5.qttools
    python312Packages.spyder
    sqlitebrowser
    # halogenOS development
    git-repo
    # Nice-to-have 3rd parties
    gimp
    xmlstarlet
    aapt
    apktool
    scrcpy
    (callPackage ../../pkgs/microsoft-edit.nix { })
  ];
}
